---
# roles/base_pi/tasks/main.yml

- name: Set up user accounts
  import_tasks: users.yml

- name: Configure SSH daemon
  import_tasks: sshd_config.yml

- name: Install base packages
  import_tasks: packages.yml

- name: Configure network
  import_tasks: network.yml

- name: Disable wireless interfaces
  import_tasks: disable_wireless.yml

- name: Deploy system message and timesync
  import_tasks: common.yml
