---
- name: Deploy custom sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: restart sshd
  become: true

- name: Restart SSH
  systemd:
    name: ssh
    state: restarted
  listen: restart sshd
  become: true
