- name: Allow passwordless sudo for admin group
  template:
    src: admin-nopasswd.j2
    dest: /etc/sudoers.d/admin-nopasswd
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  become: true
