- name: Disable WiFi interface with rfkill
  command: rfkill block wifi
  become: true
  changed_when: false
  tags:
    - wireless

- name: Mask wpa_supplicant service to prevent wireless management
  systemd:
    name: wpa_supplicant.service
    masked: yes
    state: stopped
    enabled: no
  become: true
  tags:
    - wireless

- name: Disable wireless kernel module via modprobe blacklist
  copy:
    dest: /etc/modprobe.d/disable-wireless.conf
    content: |
      # Disable wireless modules
      blacklist brcmfmac
      blacklist brcmutil
      blacklist cfg80211
      blacklist mac80211
      blacklist rfkill
  owner: root
  group: root
  mode: '0644'
  become: true
  tags:
    - wireless
