- name: Deploy Unbound main config
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy home LAN config
  template:
    src: home_lan.conf.j2
    dest: /etc/unbound/unbound.conf.d/home_lan.conf
    owner: root
    group: root
    mode: '0644'
  become: true
