- name: Deploy Unbound config
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf.d/unbound.conf
    mode: '0644'
  notify: restart unbound
  become: yes

- name: Enable Unbound service
  systemd:
    name: unbound
    enabled: yes
    daemon_reload: yes
  become: yes