- name: Ensure /etc/systemd/resolved.conf.d exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'
  become: true

- name: Deploy systemd-resolved DNS config override
  template:
    src: resolved-dns.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart systemd-resolved
