all:
  children:
    lab:
      hosts:
        pi00:
          ansible_host: 192.168.1.90
        pi01:
          ansible_host: 192.168.1.91
        pi02:
          ansible_host: 192.168.1.92
        pi03:
          ansible_host: 192.168.1.93
        pi04:
          ansible_host: 192.168.1.94
    piholes:
      hosts:
        pihole:
          ansible_host: 192.168.1.8
    print_servers:
      hosts:
        scribe:
          ansible_host: 192.168.1.83
    document_servers:
      hosts:
        scribe:
          ansible_host: 192.168.1.83
all_network_hosts:
  children:
    lab: {}
    piholes: {}
    print_servers: {}
    document_servers: {}
