- name: restart unbound
  systemd:
    name: unbound
    state: restarted
    enabled: yes
  become: true

- name: daemon-reexec
  ansible.builtin.command: systemctl daemon-reexec
  become: true

- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: true
  when: "'systemd-resolved.service' in ansible_facts.services"

