---
- name: Ensure bash is installed
  package:
    name: bash
    state: present
  become: true

- name: Copy .bashrc for {{ user.name }}
  copy:
    src: bashrc
    dest: "/home/{{ user.name }}/.bashrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0744'
  become: true

- name: Copy .bash_profile for {{ user.name }}
  copy:
    src: bash_profile
    dest: "/home/{{ user.name }}/.bash_profile"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0744'
  become: true

- name: Set shell to bash for {{ user.name }}
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
  become: true
