---
- name: Manage groups for user accounts.
  include_tasks: groups.yml

- name: Manage user accounts
  include_tasks: users.yml

- name: Load bash shell config for users
  include_tasks: bash.yml
  when: shell == 'bash'
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: Load zsh shell config for users
  include_tasks: zsh.yml
  when: shell == 'zsh'
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: Load vim config for users
  include_tasks: vim.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
