---
- name: Install zsh
  package:
    name: zsh
    state: present
  become: true

- name: Copy .zshrc for {{ user.name }}
  copy:
    src: zshrc
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
  become: true

- name: Copy .zprofile for {{ user.name }}
  copy:
    src: zprofile
    dest: "/home/{{ user.name }}/.zprofile"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
  become: true

- name: Set shell to zsh for {{ user.name }}
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
  become: true
