---
galaxy_info:
  role_name: cups
  author: Derek Dees
  description: "Installs and configures CUPS print services and Avahi for AirPrint discovery on Debian-based systems."
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - buster

dependencies: []
