---
galaxy_info:
  role_name: language_python
  author: Derek Dees
  description: Install Python via asdf with multiple versions and pip tools for each user
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
