---
galaxy_info:
  author: Your Name
  description: Role to maintain packages on Debian-based systems, including Raspbian.
  company: Your Company or Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - maintenance
    - packages
    - debian

dependencies: []
